{% set version = "0.8.0-dev" %}

package:
  name: mooda
  version: {{ version | replace("-", "")}}

source:
  path: .

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

  entry_points:
      - mooda = mooda.cli:main

requirements:
  host:
    - python
    - pip
    - setuptools
    - numpy >=1.16
    - scipy
    - biopython >=1.73
    - pandas >=0.24
    - pyyaml

  run:
    - python
    - numpy >=1.16
    - scipy
    - numpy >=1.16
    - scipy
    - biopython >=1.73
    - pandas >=0.24
    - pyyaml

test:
  commands:
    - mooda --help

about:
  home: https://github.com/stracquadaniolab/mooda
  summary: Multi-Objective Optimization for DNA design and Assembly
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/stracquadaniolab/mooda
  doc_url: https://github.com/stracquadaniolab/mooda
  description: |
    A Python tool and framework for multi-objective design and assembly of DNA constructs.

extra:
  recipe-maintainers:
    - stracquadaniolab
